import Head from "next/head";
import Banner from "../components/Banner";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rick & Morty Api</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-[1700px]">
        <section className="justify-center max-w-7xl mx-auto flex">
          <Banner />
        </section>
      </main>
    </>
  );
}
